dist: precise
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - canonical-qt5-edgers/ubuntu1204-qt5
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - canonical-qt5-edgers/ubuntu1204-qt5
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - canonical-qt5-edgers/ubuntu1204-qt5
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - canonical-qt5-edgers/ubuntu1204-qt5
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev qtdeclarative5-dev
script:
  - cd qtapp
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
